// Content snapshot: 2026-10-06. Stable task/step IDs are the persistence contract.
export const sources = {
  current: { title: 'Bungie · Monument of Triumph support guide', url: 'https://help.bungie.net/hc/en-us/articles/49848696022548-Destiny-2-Monument-of-Triumph-and-Update-9-7-0-Support-Guide', kind: 'Official', date: '2026-06-09' },
  faq: { title: 'Bungie · Returning-player FAQ', url: 'https://help.bungie.net/hc/en-us/articles/50100493304468--13-Monument-of-Triumph-FAQ', kind: 'Official', date: '2026-06' },
  patch: { title: 'Bungie · Update 9.7.0', url: 'https://www.bungie.net/7/en/News/Article/destiny_update_9_7_0', kind: 'Official', date: '2026-06-09' },
  hotfix: { title: 'Bungie · Update 9.7.0.3', url: 'https://static01.bungie.net/7/en/News/Article/destiny_2_update_9_7_0_3', kind: 'Official', date: '2026-07' },
  launch: { title: 'Bungie · Monument of Triumph overview', url: 'https://www.bungie.net/7/en/News/Article/monument_of_triumph_is_live', kind: 'Official', date: '2026-06-09' },
  armor: { title: 'Bungie · June abilities and armor changes', url: 'https://www.bungie.net/7/en/News/Article/dev_insights_abilities_armor_preview', kind: 'Official', date: '2026-06-04' },
  weapons: { title: 'Bungie · Weapons, artifacts and focusing', url: 'https://www.bungie.net/7/en/News/Article/dev_insights_weapons_artifacts_focusing_preview', kind: 'Official', date: '2026-05-28' },
  stats: { title: 'Bungie · Armor 3.0 and Rahool (9.0.0.1)', url: 'https://origin-static01.bungie.net/7/en/News/Article/destiny_update_9_0_0_1', kind: 'Official · baseline; June changes apply', date: '2025-07-15' },
  mods: { title: 'Bungie · Armor mod tuning', url: 'https://www.bungie.net/7/en/News/article/twid_07_10_2025', kind: 'Official · baseline', date: '2025-07-10' },
  renegadeArmor: { title: 'Bungie · Renegades armor tuning', url: 'https://static01.bungie.net/7/en/News/Article/dev_insight_renegades_armor', kind: 'Official · baseline', date: '2025-11-19' },
  prismatic: { title: 'Bungie · Prismatic starting kit', url: 'https://www.bungie.net/7/en/News/article/prismatic_deep_dive', kind: 'Official · unlock baseline', date: '2024-04-09' },
  heroes: { title: 'Shacknews · Destined Heroes quest', url: 'https://www.shacknews.com/article/140117/destined-heroes-ergo-sum-destiny-2', kind: 'Community walkthrough', date: '2024-06-06' },
  queens: { title: 'Destinypedia · Queens, Part I', url: 'https://www.destinypedia.com/Queens%2C_Part_I', kind: 'Community walkthrough', date: '2024' },
  wild: { title: 'D2 Wiki · Wild Card quest', url: 'https://d2.destinygamewiki.com/wiki/Wild_Card', kind: 'Community walkthrough', date: '2024 · checked 2026-10-06' },
  excision: { title: 'Shacknews · Excision access', url: 'https://www.shacknews.com/article/140188/destiny-2-excision-post-raid-mission', kind: 'Community walkthrough', date: '2024-06-09' },
  facets: { title: 'Shacknews · Prismatic unlock locations', url: 'https://www.shacknews.com/article/140091/unlock-prismatic-abilities-destiny-2', kind: 'Community walkthrough', date: '2024-06' },
  facetAudit: { title: 'Bungie Help forum · missing Prismatic unlocks', url: 'https://www.bungie.net/en/Forums/Post/265296804', kind: 'Community help · 2026 confirmation', date: '2026-06-27' },
  lawless: { title: 'Bungie · Lawless Frontier guide', url: 'https://www.bungie.net/7/en/News/Article/lawless_frontier_guide', kind: 'Official', date: '2025-12-02' },
  renLaunch: { title: 'Bungie · Renegades launch and Equilibrium access', url: 'https://www.bungie.net/7/en/News/Article/renegades_launch_blog', kind: 'Official', date: '2025-12-02' },
  intro: { title: 'ProGameTalk · 13 introduction steps', url: 'https://progametalk.com/destiny-2/renegades-introduction-quest/', kind: 'Community · auto-launch information superseded', date: '2025-12-06' },
  campaign: { title: 'ProGameTalk · Renegades mission order', url: 'https://progametalk.com/destiny-2/renegades-campaign-missions/', kind: 'Community walkthrough', date: '2026-01-21' },
  piker: { title: 'Bungie API via light.gg · Mechanic Deoriks rank rewards', url: 'https://www.light.gg/db/vendors/1305220558/mechanic-deoriks/', kind: 'Item database', date: 'Checked 2026-10-06' },
  a499: { title: 'Bungie API via light.gg · Refurbished A499', url: 'https://www.light.gg/db/items/3661051060/refurbished-a499/', kind: 'Item database · popularity is not a DPS ranking', date: 'Roll pool changed 2026-06-08' },
  aggregate: { title: 'light.gg · Aggregate Charge research', url: 'https://www.light.gg/db/items/3764420437/aggregate-charge/', kind: 'Perk description + community measurement', date: '2026-01-04' },
  accelerated: { title: 'light.gg · Accelerated Assault research', url: 'https://www.light.gg/db/items/2697390518/accelerated-assault/', kind: 'Perk description + community measurement', date: '2026-01-19' },
  a499Practice: { title: 'Community · July A499 reload and damage discussion', url: 'https://www.reddit.com/r/DestinyTheGame/comments/1v0spzf/how_to_make_a499_do_top_tier_damage/', kind: 'Community technique · test on your roll', date: '2026-07-19' },
  nighthawk: { title: 'Bungie API via light.gg · Armor 3.0 Nighthawk', url: 'https://www.light.gg/db/items/3960926756/celestial-nighthawk/', kind: 'Item database', date: '2026-06-08' },
  catalyst: { title: 'light.gg · Still Hunt catalyst', url: 'https://www.light.gg/db/items/2993090545/still-hunt-catalyst/', kind: 'Item database + community research', date: '2026-07-08' },
  hezen: { title: 'light.gg · current Hezen Vengeance pool', url: 'https://www.light.gg/db/items/2265407516/hezen-vengeance/', kind: 'Item database', date: '2026-06-08' },
  sets: { title: 'light.gg · current armor set bonuses', url: 'https://www.light.gg/armor/set-bonuses/', kind: 'Item database', date: 'Checked 2026-10-06' },
  spireSet: { title: 'light.gg · High Noon / TM Custom', url: 'https://www.light.gg/db/items/3540897637/', kind: 'Hunter armor item database', date: '2026-06-08' },
  reload: { title: 'light.gg · Reload at Range', url: 'https://www.light.gg/db/items/3834273541/reload-at-range/', kind: 'Item database', date: '2026-06-22' },
  disk: { title: 'light.gg · artifact database (current versions)', url: 'https://www.light.gg/db/all?f=12%28sniper%29', kind: 'Item database · use S29 versions', date: 'Checked 2026-10-06' },
  cipher: { title: 'Bungie API via light.gg · Exotic Cipher', url: 'https://www.light.gg/db/items/3467984096/exotic-cipher/', kind: 'Item database', date: '2026-06-08' },
  vault: { title: 'Bungie · Destiny Content Vault', url: 'https://help.bungie.net/hc/en-us/articles/360049202971-Destiny-Content-Vault', kind: 'Official', date: 'Living reference' },
  glimmer: { title: 'Bungie · Update 7.3.4 (Glimmer cap)', url: 'https://www.bungie.net/7/en/News/Article/destiny_2_update_7_3_4', kind: 'Official · unchanged cap baseline', date: '2024-01-30' },
  chroma: { title: 'light.gg · current Chroma Rush', url: 'https://www.light.gg/db/items/771811871/chroma-rush/', kind: 'Item database', date: 'Checked 2026-10-06' },
  inbound: { title: 'light.gg · current Inbound Surveillance', url: 'https://www.light.gg/db/items/2776506837/inbound-surveillance/', kind: 'Item database', date: 'Checked 2026-10-06' },
  moonStory: { title: 'Shacknews · Shadowkeep quest route', url: 'https://www.shacknews.com/article/114274/destiny-2-shadowkeep-campaign-walkthrough', kind: 'Legacy walkthrough · old Power values superseded', date: '2019-10-01' },
  europaStory: { title: 'Gamepur · Beyond Light quest sequence', url: 'https://www.gamepur.com/GUIDES/DESTINY-2-BEYOND-LIGHT-MISSION-LIST-ALL-MISSIONS-IN-THE-STORY-CAMPAIGN', kind: 'Legacy walkthrough · old Power values superseded', date: '2023-03-15' },
  witchStory: { title: 'Shacknews · Witch Queen mission sequence', url: 'https://www.shacknews.com/article/128952/destiny-2-the-witch-queen-campaign-walkthrough', kind: 'Legacy walkthrough · old reward costs superseded', date: '2022-02-25' },
  lightfallStory: { title: 'Shacknews · Lightfall mission sequence', url: 'https://www.shacknews.com/article/134362/destiny-2-lightfall-campaign-guide', kind: 'Legacy walkthrough', date: '2023-03-06' },
  keplerStory: { title: 'Shacknews · Edge of Fate campaign and puzzles', url: 'https://www.shacknews.com/article/145105/destiny-2-the-edge-of-fate-campaign-guide', kind: 'Community walkthrough · non-linear campaign', date: '2025-07-15' },
  infusion: { title: 'Bungie · Infusion and retired Unstable Cores', url: 'https://www.bungie.net/7/en/News/Article/destiny_update_9_1_5_2', kind: 'Official', date: '2025-10-21' }
};

export const sections = [
  ['position', 'Your starting point', 'Confirm what you have, then pick up the post-campaign thread.'],
  ['finale', 'Still Hunt & the finale', 'The shortest route from Iconoclasm to your Exotic sniper.'],
  ['prismatic', 'Prismatic unlock audit', 'Start with the kit already unlocked. Add utility when it helps.'],
  ['nighthawk', 'Celestial Nighthawk', 'Get a working helmet first. Tune the whole loadout later.'],
  ['renegades', 'Renegades → A499', 'Introduction, Piker access, first copy, then a sensible farming stop.'],
  ['build', 'Loadouts & armor', 'A usable setup now, a finished A499 setup, and optional refinement.'],
  ['rotation', 'DPS practice', 'Practice the loop and the recovery, not just the perfect opener.'],
  ['hezen', 'Hezen burst variant', 'A secondary rocket loadout. A499 remains the main heavy.'],
  ['endgame', 'After A499 · endgame', 'Spend your next sessions on upgrades that actually change the build.'],
  ['story', 'After A499 · story', 'Catch up in release order, with vaulted chapters kept separate.'],
  ['cleanup', 'Quest-log cleanup', 'Decide what to keep, park, or recover later.'],
  ['raids', 'Raid record', 'Every available full raid, plus the permanent Pantheon activity.'],
  ['dungeons', 'Dungeon record', 'Every available dungeon, grouped by its story era.'],
  ['materials', 'Resources & spending', 'Manual inventory counts start unknown, not at zero.'],
  ['watchlist', 'Keep this loot', 'Lock useful rolls before dismantling a batch.']
].map(([id, title, description]) => ({ id, title, description }));

export const tasks = [];
function task(id, section, title, steps, options = {}) {
  tasks.push({ id, section, title, steps: steps.map((text, i) => typeof text === 'object' ? { id: `${id}.${i + 1}`, ...text } : { id: `${id}.${i + 1}`, text }),
    requires: [], tags: [], priority: 500, branch: null, tier: 'Useful', location: 'See steps', reward: 'Progress recorded', why: 'Keep the next session focused.',
    time: '15–30 min', team: 'Solo', gate: 'None', sources: [], ...options });
}
const critical = { tags: ['Build Critical'], tier: 'Required for this route' };

task('iconoclasm', 'position', 'Iconoclasm completed', [{ text: 'Iconoclasm is complete on this Hunter. This is your reported starting point.', initial: true }], { ...critical, priority: 0, location: 'The Pale Heart', time: 'Already done', reward: 'Campaign mission 7 complete', why: 'The mission is named Iconoclasm; it opens the post-campaign route. Excision is still ahead.', sources: ['queens'] });
task('audit', 'position', 'Take a two-minute inventory', [
  'Open Quests and track The Final Shape / Destined Heroes. Compare the objective with the finale section below; do not replay completed missions.',
  'Check Collections, vault and character for Celestial Nighthawk and Still Hunt. Mark their acquisition tasks complete if already owned.',
  'Check Prismatic on this Hunter. Fragments are shared across characters; ability and Aspect completion is per character.',
  'Open Director → Raids and Dungeons and confirm owned Dungeon Keys. The Collection includes them; similarly named legacy collections may differ.',
  'Enter your actual resources in Inventory. Leave anything you have not checked blank.'
], { ...critical, priority: 1, requires: ['iconoclasm'], time: '2–5 min', reward: 'Known starting inventory', sources: ['current', 'facetAudit'] });
task('current-system', 'position', 'Orient to October 2026', [
  'Use Destinations for Kepler, the Lawless Frontier, and Ops. Use Raids and Dungeons for full activities.',
  'Read the Sources page if an old guide mentions Portal-only navigation, armor Resilience tiers, or seasonal Champion weapon mods.',
  'Treat the checklist as a manual record. It does not read your Bungie account or track live vendor offers.'
], { tags: ['Optional'], tier: 'Reference', recommend: false, time: '5 min', reward: 'Current menu orientation', why: 'Monument of Triumph is permanent. Older onboarding guides can send you to retired menus.', sources: ['current', 'faq'] });

task('heroes-radio', 'finale', 'Listen to the Lost City radio', ['Return to the Lost City Tower in the Pale Heart after Iconoclasm.', 'Speak with Ghost and listen to the radio beside him to begin Destined Heroes. Track that quest.'], { ...critical, tags: ['Build Critical', 'Story'], priority: 2, requires: ['audit'], location: 'Pale Heart → Lost City Tower', time: '5 min', reward: 'Destined Heroes', why: 'This is the route to Wild Card; finishing the entire Ergo Sum chain first is unnecessary.', sources: ['heroes'] });
task('queens-one', 'finale', 'Complete Queens, Part I', ['Launch Queens, Part I from its Lost City adventure banner.', 'Use the Hive sword guard to reflect projectiles as the objective instructs; clear the rituals and finish the adventure.', 'Visit Micah-10 at the Arbor of Light conduit when Destined Heroes directs you there. Accept Convalescence: Rootbound; park that side quest for later.'], { ...critical, tags: ['Build Critical', 'Story'], priority: 3, requires: ['heroes-radio'], time: '20–35 min', team: 'Solo or 1–3', location: 'Lost City / The Refraction', reward: 'Post-campaign quest advance', sources: ['queens', 'heroes'] });
task('wild-accept', 'finale', 'Get Wild Card from Cayde-6', ['Speak to Cayde-6 in the Lost City Tower after the preceding Destined Heroes objectives.', 'Accept Wild Card. Continue Ghost dialogue if the quest asks for it, then find the rooftop mission banner.', 'If the quest is missing, check Quests and the Quest Archive before repeating activities. Follow your displayed Destined Heroes objective.'], { ...critical, tags: ['Build Critical', 'Exotic'], priority: 4, requires: ['queens-one'], time: '5–10 min', reward: 'Wild Card mission access', sources: ['wild', 'heroes'] });
task('still-hunt', 'finale', 'Finish Wild Card and claim Still Hunt', ['Launch Wild Card from the rooftop banner in the Lost City Tower.', 'Follow Cayde and Crow: gather Dark Ether, establish camp, investigate the source, and clear the marked threats.', 'Finish the mission’s final fight against Lii’liks, Harvester of the Witness. Stay at range when waves crowd you.', 'Return to the Lost City radio and speak with Cayde-6. Claim Still Hunt and lock it.'], { ...critical, tags: ['Build Critical', 'Exotic', 'Story'], priority: 5, requires: ['wild-accept'], time: '35–60 min', team: 'Solo or 1–3', location: 'Pale Heart → Wild Card', reward: 'Still Hunt · Exotic Solar energy sniper', why: 'One deterministic quest replaces a long Exotic weapon farm. No raid completion is required.', sources: ['wild'] });
task('excision', 'finale', 'Finish The Final Shape with Excision', ['With Wild Card finished, find Excision at the far right of the Pale Heart map.', 'Launch the narrative version and follow the encounter prompts through the finale.', 'Let the ending cinematics play; return to Ghost and collect any pending campaign completion rewards.'], { tags: ['Story'], priority: 5.5, requires: ['still-hunt'], location: 'Pale Heart → Excision', time: '25–45 min', team: '12-player matchmade', reward: 'Light and Darkness saga finale', why: 'Iconoclasm is not the final narrative ending. Your own Salvation’s Edge clear is not a prerequisite.', sources: ['excision'] });
task('ergo-chain', 'finale', 'Finish Destined Heroes for Ergo Sum', ['Take Lost in the Light and Found in the Dark from Ghost when offered.', 'Lost in the Light: complete The Hollow, Part I and Part II, returning for quest dialogue as prompted.', 'Found in the Dark: complete Home, Part I and Part II and the intervening quest objectives.', 'Complete Queens, Part II; speak to Ghost and receive the Dyadic Prism.', 'Travel to the Sacrarium and interact with the marked object to claim Ergo Sum.'], { tags: ['Exotic', 'Prismatic', 'Optional', 'Story'], tier: 'Optional for Nighthawk', requires: ['still-hunt'], time: '2–3 hr', team: 'Solo or 1–3', reward: 'Ergo Sum and remaining Prismatic abilities', why: 'A useful alternate loadout, but it occupies Still Hunt’s Exotic weapon slot.', sources: ['heroes', 'facetAudit'] });
task('convalescence', 'finale', 'Micah-10 and Microcosm cleanup', ['Finish Convalescence: Rootbound, Underbrush and Greenery in order, following Micah-10’s Ghost recovery and Overthrow objectives.', 'Accept Convalescence: Budding and assemble a communicating three-player fireteam.', 'Complete the cooperative focus versions of Ascent, Dissent and Iconoclasm; these add shared mechanics and are not ordinary campaign replays.', 'Return to Micah-10 for Microcosm. Park the quest until friends are available.'], { tags: ['Exotic', 'Optional', 'Story'], requires: ['excision'], tier: 'Later', team: '3 recommended; coordinated mechanics', time: '2–4 hr', reward: 'Microcosm', sources: ['current'], note: 'Exact quest counters are shown by your quest card. Microcosm cannot be equipped alongside Still Hunt.' });

task('prism-core', 'prismatic', 'Equip the starting Prismatic damage kit', ['Super: Golden Gun — Marksman. Keep Celestial’s single precision shot in mind; do not select Silence and Squall for this loadout.', 'Class ability: Marksman’s Dodge for emergency reload. Use Gambler’s Dodge as a separate roaming variant when melee uptime matters.', 'Melee: Withering Blade to apply Slow; Knife Trick is an alternative when you want Scorch and an easy Radiant trigger.', 'Grenade: Duskfield for control and a Darkness debuff. Swarm is an available Solar alternative.', 'Aspects: Stylish Executioner + Winter’s Shroud. Debuff a minor enemy, defeat it, then reposition while invisible.', 'Movement: use the jump you land reliably. All listed choices are starting unlocks from the Transmigration Prismatic encounter.'], { ...critical, tags: ['Build Critical', 'Prismatic'], priority: 6, requires: ['audit'], time: '5–10 min', reward: 'Functional starting subclass', why: 'You can start the build without unlocking every ability. Neither Stasis nor Strand campaign completion is needed for these Prismatic options.', sources: ['prismatic'] });
task('prism-facets', 'prismatic', 'Audit the five starting fragments', ['Facet of Dawn: powered melee hits grant Radiant. Use this if teammates do not provide a reliable damage buff.', 'Facet of Courage: your Light abilities benefit against Darkness-debuffed targets. Slow with Withering Blade before your actual Golden Gun.', 'Facet of Purpose: Orbs give a defensive buff based on your Super; Golden Gun gives Restoration.', 'Facet of Protection: useful damage resistance when surrounded. It does not replace cover or encounter mechanics.', 'Facet of Hope: positive subclass buffs help your class ability recharge. Equip these five and inspect the slot count; use starting Ruin in an extra slot if your chosen Aspects allow it.'], { ...critical, tags: ['Build Critical', 'Prismatic'], priority: 7, requires: ['prism-core'], time: '5 min', reward: 'Starting fragment loadout', why: 'These are starting fragments, not hidden-chest farms. No fragment is required for the Nighthawk/Still Hunt interaction itself.', sources: ['prismatic'], note: 'Courage applies to the actual Hunter Super. Do not assume every Super-related bonus applies to Still Hunt’s weapon shot.' });
task('threaded-spike', 'prismatic', 'Useful: unlock Threaded Spike', ['Progress Found in the Dark / Home, Part I from Ghost’s post-campaign quests.', 'Finish Home, Part I and open its Prismatic reward chest on this Hunter.', 'Equip Threaded Spike when a returning ranged melee and Sever suit the encounter better than Withering Blade.'], { tags: ['Prismatic', 'Optional'], requires: ['still-hunt'], time: '20–35 min', reward: 'Threaded Spike', sources: ['facetAudit', 'facets'], note: 'On a second character, replay the Home I banner at the Lost City. Fragments transfer between characters; this melee does not.' });
task('gunpowder', 'prismatic', 'Useful: unlock Gunpowder Gamble', ['Progress Lost in the Light / The Hollow, Part I from Ghost.', 'Complete The Hollow, Part I and claim its Prismatic reward chest on this Hunter.', 'Use Gunpowder Gamble instead of Winter’s Shroud for more add clear once you can survive comfortably. Read the grenade HUD before throwing.'], { tags: ['Prismatic', 'Optional'], requires: ['still-hunt'], time: '20–35 min', reward: 'Gunpowder Gamble Aspect', sources: ['facetAudit', 'facets'] });
task('grace', 'prismatic', 'Useful: find Facet of Grace', ['Start in the Lost City patrol area and find the Prismatic encounter near the outer rooftops.', 'Defeat the encounter’s marked enemies and Tormentor; collect the Lost City Prismatic Key and open the chest.', 'Consider Grace for Transcendence generation with a Kinetic primary and A499. It is an optional swap for a starting fragment.'], { tags: ['Prismatic', 'Optional'], requires: ['still-hunt'], time: '15–30 min', reward: 'Facet of Grace', sources: ['facets'] });
task('prism-rest', 'prismatic', 'Optional: finish the Hunter ability audit', ['Campaign reward chests: check Combination Blow, Grapple, Ascension, Storm’s Edge, Arcbolt and Snare Bomb. Replay the campaign reward encounters on this Hunter if missing.', 'Home I / II supply the remaining Darkness branch: Threaded Spike and Silkstrike. Queens I / II supply remaining Aspect rewards. The Hollow I / II supply the Light branch including Magnetic Grenade and Deadfall.', 'Launch incomplete Home, Queens and The Hollow banners at the Lost City on alternate characters; hover their rewards rather than starting Micah’s whole quest chain again.', 'Check the subclass grid afterward. Full completion is optional for this sniper build.'], { tags: ['Prismatic', 'Optional'], requires: ['still-hunt'], time: '2–4 hr if most are missing', reward: 'Full Hunter Prismatic ability menu', sources: ['facetAudit', 'prismatic'] });
task('facet-chests', 'prismatic', 'Optional: Pale Heart fragment collection', ['Campaign hidden chests: Bravery in Ascent (drop below the broken plane route), Devotion in Dissent (detour before the exit), Sacrifice in Iconoclasm (side room before the final encounter).', 'Open-world Prismatic encounters: Grace in Lost City, Mending in Lost City Outskirts, Justice in The Refraction, Command in The Divide, Defiance in The Transgression.', 'Justice uses the Hive-rune brazier puzzle; Command uses ice, a Scorch Cannon and elemental charges. Use the linked illustrated guide for the room layouts.', 'Memory Vestige: Light → five vestiges form a Legendary Light Memory for Awakening, Generosity or Dominance. Earn them from glowing enemies in Cysts.', 'Memory Vestige: Darkness → five vestiges form a Legendary Dark Memory for Honor or Solitude. Earn them from corrupted chest encounters.', 'Follow the Memory’s named map area; open its Prismatic chest before collecting more. Check Multifaceted in Triumphs to find missing encounters.'], { tags: ['Prismatic', 'Optional'], requires: ['still-hunt'], time: '3–6 hr', reward: 'All 21 fragments audit', why: 'Dominance is useful with Magnetic/Arcbolt, while Grace supports Kinetic damage. The starting kit works before this collection.', sources: ['facets', 'facetAudit'], note: 'Use your actual Memory item and quest card if vestiges stop converting; do not delete a pile of items based on a generic checklist.' });

task('nighthawk-owned', 'nighthawk', 'Acquire any working Celestial Nighthawk', ['If you already own Nighthawk, equip it now. A Collections copy is sufficient to test the interaction.', 'If missing, visit Rahool at the Tower as Hunter. Check Novel Exotic focusing: past-expansion Exotics no longer require a reputation reset.', 'Budget one Exotic Engram and one Exotic Cipher for Novel focusing; inspect the Nighthawk offer before spending. Choose a useful archetype if offered.', 'Alternative: buy Nighthawk from Xûr when stocked, or decrypt Hunter Exotic Engrams. Stock and random drops are not guaranteed on a specific day.', 'Equip and lock the helmet. Leave the perfect roll hunt until the weapons work.'], { ...critical, tags: ['Build Critical', 'Exotic', 'Farming'], priority: 8, requires: ['audit'], time: '5–15 min if resources ready; RNG otherwise', location: 'Tower → Rahool / Xûr', gate: 'Xûr rotates; engrams may be RNG', reward: 'Celestial Nighthawk', sources: ['stats', 'nighthawk', 'cipher'], note: 'Current vendor price is authoritative. The resource tracker is a planning reserve, not an automatic purchase calculator.' });
task('nighthawk-tune', 'nighthawk', 'Tune an Armor 3.0 Nighthawk', ['Inspect your copy: verify Armor 3.0 rather than an old raid-era version or a Collections roll.', 'Use a non-Collections Armor 3.0 copy for Tier 5 stats and access to all tuning mods. Existing eligible copies received this retroactively.', 'Pick +5/−5 tuning that improves your whole equipped loadout, or Balanced Tuning. Tuning does not freely redistribute the entire stat roll or change its archetype.', 'If the archetype is wrong, focus another copy with a chosen archetype; Powerhouse emphasizes Weapons and Super. Keep the working copy until the replacement is tested.', 'Avoid paying for an Armor 2.0 Artifice slot expecting Armor 3.0 tuning. The systems differ.'], { tags: ['Exotic', 'Farming', 'Optional'], requires: ['nighthawk-owned'], tier: 'Min-max', time: '10 min plus focusing', gate: 'Random tertiary/stat profile', reward: 'Better stat fit', sources: ['armor', 'renegadeArmor', 'stats'] });

task('temporary', 'build', 'Save the pre-A499 loadout', ['Kinetic slot: a Legendary primary you can use safely. Chroma Rush with Kinetic Tremors is a good target; a reliable owned primary is enough.', 'Energy slot: Still Hunt. Heavy slot: an owned Legendary rocket, linear fusion, or machine gun appropriate to the encounter.', 'Equip Nighthawk and the starting Prismatic kit. Do not equip a second Exotic weapon or armor piece.', 'Add a matching Siphon, useful weapon loaders, chest resistances and an orb-healing option. Test in ordinary PvE before harder missions.', 'Save the loadout as “Nighthawk · interim” in-game.'], { ...critical, priority: 9, requires: ['still-hunt', 'nighthawk-owned', 'prism-facets'], time: '10–15 min', reward: 'Functional temporary build', why: 'You should be able to play and learn while acquiring A499; a perfect primary is not a prerequisite.', sources: ['nighthawk', 'prismatic', 'mods'] });

task('ren-start', 'renegades', 'Start Renegades manually', ['Select Renegades / Lawless Frontier in Destinations and track the Renegades introduction quest.', 'Complete Imperium, the opening mission. Older guides describing forced auto-launch are out of date.', 'Speak with Commander Zavala at the Tower, then visit Drifter in the Tharsis Cantina.'], { ...critical, tags: ['Build Critical', 'Story'], priority: 10, requires: ['temporary'], location: 'Director → Lawless Frontier / Tower / Tharsis', time: '25–45 min', team: 'Solo or 1–3', reward: 'Renegades introduction progression', why: 'For this route, you are jumping ahead for the weapon. Edge of Fate comes first narratively, but is not listed here as an access requirement.', sources: ['intro', 'patch', 'renLaunch'], note: 'Renegades ownership and a completed New Light onboarding state are the relevant access checks. Follow a displayed onboarding blocker if your character has one.' });
task('ren-cantina', 'renegades', 'Complete the Cantina introduction', ['Visit the Piker Bouncer.', 'Speak to Aunor at the marked seat in the Cantina.', 'Speak to Drifter’s Ghost, then Drifter.', 'Access Drifter’s recording.', 'Find the marked Ghost parts at the Bazaar Armorers, Scrap Mercantile and Unpaired Ghost Commune.', 'Ask Spider for help in the Tharsis Cantina.'], { ...critical, tags: ['Build Critical', 'Story'], priority: 11, requires: ['ren-start'], time: '15–25 min', location: 'Tharsis Cantina and Bazaar', reward: 'Welcome to the Frontier access', sources: ['intro'] });
task('ren-welcome', 'renegades', 'Complete Welcome to the Frontier', ['Launch Welcome to the Frontier for Spider.', 'Follow the courier/package objectives and exfiltrate with the package.', 'Return to Spider for the remaining Ghost components.', 'Visit Drifter’s Ghost / Blue and claim the introduction reward. Track the main Renegades campaign quest.'], { ...critical, tags: ['Build Critical', 'Story'], priority: 12, requires: ['ren-cantina'], time: '25–45 min', team: 'Solo or 1–3', location: 'Lawless Frontier → Tharsis Cantina', reward: 'Introduction complete; main campaign quest', sources: ['intro', 'lawless'] });
task('piker-rank', 'renegades', 'Open the Piker A499 shop at Rank 2', ['Visit Mechanic Deoriks / the Piker den and War Chest at Tharsis. Inspect the rank track.', 'Run available Lawless Frontier jobs and contracts; collect Credits and Dark Matter Ingots.', 'Deposit Ingots in the Piker War Chest for reputation and a chance at Piker gear, including A499.', 'Reach Piker Rank 2 and confirm the gear shop can sell Refurbished A499 for Credits. Record your rank in Inventory.'], { ...critical, tags: ['Build Critical', 'Farming'], priority: 13, requires: ['ren-welcome'], time: '1–3 hr estimate; varies by contracts', location: 'Tharsis → Pikers / Lawless Holomap', team: 'Solo or 1–3', gate: 'Random loot; rank access deterministic', reward: 'Direct A499 purchasing', why: 'This is a specific Piker reputation gate, not Guardian Rank 2 and not a generic Fallen rank.', sources: ['piker', 'lawless'], note: 'You can gain reputation before completing the main story. Alliance banners and daily Priority Contracts unlock after that story; they are a later farm improvement.' });
task('a499-first', 'renegades', 'Get a first usable Refurbished A499', ['Inspect the Piker shop’s A499 offer and current Credit cost. Use its limited daily discount if available.', 'Buy an A499, or keep one obtained from the Piker War Chest / eligible Lawless rewards.', 'Check that it is the Kinetic heavy Disruption sniper; it does not compete with Still Hunt’s energy slot.', 'Lock a usable copy. A lower-tier copy is enough to learn the reload loop; do not dismantle it while chasing a perfect one.'], { ...critical, tags: ['Build Critical', 'Farming'], priority: 14, requires: ['piker-rank'], time: '5–15 min with Credits; RNG for chosen roll', location: 'Piker gear shop', reward: 'Refurbished A499', gate: 'Perks random; discounted purchases limited daily', sources: ['piker', 'a499'], note: 'No fixed Credit cost is hardcoded: the vendor’s price can depend on the current offer and discount. Enter a farming budget in Inventory.' });
task('a499-roll', 'renegades', 'Keep the right A499 roll and set a stopping point', ['Preferred practical PvE target: Snapshot Sights + Aggregate Charge, with Flared Magwell and a Reload masterwork if available. Snapshot is convenience; Aggregate is the important damage perk.', 'Keep any Aggregate Charge roll while learning. Bewildering Burst or Lone Wolf are acceptable third-column alternatives; compare how they feel.', 'Keep an Auto-Loading Holster roll as a swapping alternative. It competes with Aggregate in the fourth column; you cannot assume both are on one roll.', 'Gutshot Straight helps body shots and penalizes aim assistance. It is not a precision-damage bonus; prefer easier crits for this build.', 'Test with actual debuffs. Aggregate depends on distinct elemental debuffs on the target, not just your Radiant buff.', 'Stop the build-critical hunt with a functioning copy and a practiced loop. Keep the perfect roll as an optional farm.'], { ...critical, tags: ['Build Critical', 'Farming'], priority: 15, requires: ['a499-first'], time: '10–20 min audit; roll farm unbounded', gate: 'RNG; no guaranteed roll or drop percentage', reward: 'A locked usable roll and a clear stop', why: 'The recommended roll is a practical choice, not a claimed universal October DPS winner.', sources: ['a499', 'aggregate', 'a499Practice'] });
task('ren-campaign', 'renegades', 'Finish the main Renegades story for the farm tools', ['Continue the campaign’s marked jobs and dialogue between its named missions.', 'Complete Fearsome Retainer → Out in the Cold → Fire and Ice (Praxic Blade) → The Long Con → Glory Beyond in quest order.', 'Return to Spider / Drifter for the quest’s final dialogue and rewards.', 'Confirm Syndicate alliance banners and daily Priority Contracts are now available.'], { tags: ['Story', 'Farming'], priority: 130, requires: ['ren-welcome'], time: '4–7 hr', team: 'Solo or 1–3', reward: 'Full story, Praxic Blade, alliance tools', sources: ['campaign', 'lawless'], note: 'Completing every campaign mission is not imposed as a prerequisite to buying the first Rank 2 A499. The in-game campaign also interleaves jobs and conversations.' });
task('a499-farm', 'renegades', 'Optional: improve A499 without wasting Credits', ['Ally with Pikers after the story. Take the daily Priority Contract, combine it with compatible jobs, and finish the exfil.', 'Spend Ingots on Piker reputation. Rank 4 offers two discounted A499 purchases per day; Rank 5 offers three.', 'Use the highest job difficulty you can finish reliably. Read the reward preview and use Spider’s title-earned gear-tier token if unlocked.', 'Check Spider’s weekly offerings / Infamous rewards for an eligible A499 preview. Keep any copy with Accelerated Assault; its presence must be inspected.', 'Set a Credit budget and stop when it is spent. Come back for discounts rather than buying indefinitely.', 'If your desired roll is lower tier, use weapon Tier Upgrading. It enhances the existing roll but does not add alternative perks; inspect costs first.'], { tags: ['Farming', 'Optional'], tier: 'Min-max', requires: ['a499-roll', 'ren-campaign'], time: '20–60 min per session', team: 'Solo or 1–3', gate: 'Perks/origin trait RNG; daily discounts and weekly offers', reward: 'Better A499 / multiperk choices', sources: ['piker', 'weapons', 'lawless'], note: 'A red Tier 5 ornament alone does not prove Accelerated Assault. The precise October Infamous reward preview needs your in-game confirmation.' });
task('accelerated', 'renegades', 'Optional: audit Accelerated Assault', ['Inspect the origin-trait row on every A499 before dismantling.', 'Keep a copy with Accelerated Assault even if its other perks are imperfect; test its sustained-damage reload benefit.', 'Single-shot weapons do not receive the multi-shot magazine refill. Practice manual reloads rather than expecting this trait to auto-load A499.', 'Do not assume Tier Upgrading or equipping the Infamous ornament will create a missing origin trait. Read the upgrade preview.'], { tags: ['Farming', 'Optional'], tier: 'Min-max', requires: ['a499-first'], time: '5 min audit; RNG to acquire', reward: 'Correct origin-trait expectations', gate: 'Special origin trait acquisition varies by reward source', sources: ['accelerated', 'a499Practice', 'weapons'] });

task('finished-loadout', 'build', 'Save the finished A499 loadout', ['Kinetic: Legendary primary. Energy: Still Hunt. Heavy: Refurbished A499. Armor Exotic: Celestial Nighthawk.', 'Prismatic: Marksman Golden Gun, Marksman’s Dodge, Withering Blade, Duskfield, Stylish Executioner and Winter’s Shroud.', 'Fragments: Dawn, Courage, Purpose, Protection and Hope; use Grace/Ruin if you have another slot and it fits the fight.', 'Set Kinetic loaders for A499 and Solar support for Still Hunt. Choose the leg setup after testing the rotation below.', 'Save “Nighthawk · A499” in-game, including its artifact selections. Test a complete phase before spending on masterworks.'], { ...critical, priority: 16, requires: ['a499-roll', 'temporary'], time: '10–15 min', reward: 'Main loadout saved', why: 'This is the functional finish line. The next sections improve consistency rather than block you from playing.', sources: ['prismatic', 'a499', 'nighthawk', 'weapons'] });
task('mods-core', 'build', 'Fit the required mod jobs', ['Helmet: use a Siphon matching the primary you actually kill with. Keep Heavy Ammo Finder / Scout if they fit and benefit the fireteam.', 'Arms: Kinetic Loader for A499, then Solar Loader or Dexterity if Still Hunt handling is the limiting step.', 'Chest: choose resistances for the encounter’s incoming damage and range. Staying alive is worth more than an unused reserve bonus.', 'Legs: begin with orb healing and Solar Holster for the Still Hunt swap loop. Add Kinetic Weapon Surge for A499 when energy permits.', 'Class item: Time Dilation for longer Armor Charge duration if using surges; add a utility mod that fits your dodge loop.', 'Check the current mod energy costs in the armor screen. Never sacrifice the one reload/holster interaction you rely on just to copy someone’s three-surge setup.'], { ...critical, priority: 17, requires: ['finished-loadout'], time: '10–20 min', reward: 'Ammo, reload, survival and damage support', sources: ['mods', 'renegadeArmor'], note: 'This is a recommended allocation, not a fixed universal mod grid. Available armor energy and your healing sources determine the final fit.' });
task('stat-plan', 'build', 'Set current stats around the weapons', ['Read the six current stats: Weapons, Health, Class, Melee, Grenade and Super. Each point counts; 100 and 200 separate benefit ranges.', 'Build toward Weapons 100 first for handling/reload, then consider Weapons 200 for boss-weapon damage and ammo benefits.', 'Raise Super beyond 100 when you want more actual Golden Gun damage. Treat Still Hunt as a weapon when planning stat bonuses.', 'Keep enough Health, Class and melee uptime to stay alive and refresh Dawn. Avoid trading survivability for a theoretical second Super.', 'Put your measured stats in Inventory and compare the actual equipped totals after fragments and mods. The suggested targets are planning goals, not unlock requirements.'], { ...critical, priority: 18, requires: ['mods-core'], time: '10–15 min', reward: 'A stat plan using Armor 3.0', sources: ['stats', 'armor', 'renegadeArmor'], note: '200 Weapons + 200 Super is an eventual damage-focused target, not a prerequisite. June reduced boss-damage Super generation; do not copy pre-June super-spam promises.' });
task('artifact-main', 'build', 'Choose an artifact for the actual rotation', ['Inspect the current S29 Encrypted Data Disk in the artifact picker. For A499, prioritize Sniper’s Meditation and Reload at Range when offered, then compatible Kinetic/ammo utility.', 'Compare Hunter’s Journal for Solar Still Hunt support, including its sniper and Solar interactions. Choose one artifact; do not combine perks from two different artifacts.', 'Read every selected perk’s current tooltip. The available artifacts were reworked for Monument of Triumph; old seasonal grids are not the same.', 'Save the chosen artifact and perks into “Nighthawk · A499”. Use the weapon Champion icons and character tooltip to check coverage.'], { ...critical, priority: 19, requires: ['finished-loadout'], time: '5–10 min', reward: 'Artifact selection recorded', sources: ['weapons', 'disk', 'reload'], note: 'The exact selected S29 perk grid needs an in-game check. The checklist names the relevant effects without pretending an older artifact database row is a complete current loadout.' });
task('surge-compare', 'build', 'Optional: compare two leg setups', ['Setup A: Kinetic Surge, Solar Holster and an orb-healing option. Prioritize uninterrupted A499/Still Hunt swapping.', 'Setup B: heavier Kinetic Surge investment for A499-led sustained damage; account for how Still Hunt gets its sixth round.', 'For a Still Hunt-led or Hezen Solar phase, try Solar Surges instead. Elemental matching matters: Kinetic surges do not buff Still Hunt.', 'Run both against the same boss at the same difficulty, with the same buffs and phase length. Keep the setup with the more reliable result.'], { tags: ['Optional', 'Farming'], requires: ['mods-core'], time: '20–40 min', reward: 'Measured leg setup', sources: ['mods', 'a499Practice'] });
task('catalyst-still', 'build', 'Optional: finish Still Hunt’s catalyst', ['Inspect Still Hunt’s catalyst source in Collections; check Xûr’s Strange Gear Offers if it is sold that weekend.', 'When acquired, defeat 500 targets with Still Hunt, then apply the catalyst.', 'Lucky Shot needs a precision final blow followed by a reload before precision hits refill rounds from reserves.', 'Practice that activation only if the encounter supplies a safe add before damage. Do not treat it as unconditional boss auto-reloading.'], { tags: ['Exotic', 'Optional', 'Farming'], tier: 'Useful, not required', requires: ['still-hunt'], time: '45–90 min kills; acquisition may vary', gate: 'Acquisition RNG / rotating Xûr stock', reward: 'Lucky Shot', sources: ['catalyst'] });

task('dps-prep', 'rotation', 'Practice the pre-DPS setup', ['Rally when the activity allows it, or collect ammo before the phase. Confirm both reserve counts.', 'Charge Cayde’s Retribution through precision hits / Orbs and verify the weapon’s meter; check your actual Golden Gun is ready separately.', 'Agree on the team’s damage buff and debuff source. Apply Slow with Withering Blade / Duskfield for Courage and Aggregate when appropriate.', 'Use a powered melee hit to gain Dawn’s Radiant if no teammate buff is covering you. Collect Orbs for Armor Charge and healing.', 'Choose a safe line to the boss crit spot, then wait for the boss to become damageable.'], { ...critical, priority: 20, requires: ['mods-core', 'stat-plan', 'artifact-main'], time: '10–15 min practice', team: 'Solo practice; coordinate in fireteam', reward: 'Repeatable setup', why: 'A prepared shot is worth more than spending the first seconds of a phase searching for a buff.', sources: ['aggregate', 'a499Practice'], note: 'These are coaching steps, not a frame-perfect DPS record. Confirm your actual buff timers and meter behavior.' });
task('dps-open', 'rotation', 'Practice an opening burst', ['When the crit spot is exposed, activate and fire the charged Still Hunt shot accurately.', 'Cast the actual Golden Gun and land the Nighthawk precision shot while the planned buff/debuff is active.', 'Swap to A499 and fire. Manually reload immediately; fire again only when ammo has returned to the magazine.', 'Record whether this order fits the encounter. Precasting Golden Gun may suit a short window, but avoid letting the Super expire while waiting.'], { ...critical, priority: 21, requires: ['dps-prep'], time: '10–15 min', reward: 'Opening sequence learned', sources: ['nighthawk', 'a499Practice'] });
task('dps-loop', 'rotation', 'Practice the sustained A499 / Still Hunt loop', ['Use A499 shots with manual reloads during your heavy window; keep hits accurate and reapply debuffs only when worth the interruption.', 'Use regular Still Hunt precision shots to recharge Cayde’s Retribution. Read its meter rather than blindly counting after missed shots.', 'When Still Hunt is one round short, stow it long enough for Solar Holster while firing/reloading A499. Confirm the missing round has loaded.', 'Return to Still Hunt, finish charging and use its special reload input to activate the charged shot. Repeat while ammo and the phase last.', 'Only try reload animation shortening after you can complete the ordinary loop reliably. Practice the visible ammo transition, not a scripted delay.', 'Record three clean practice attempts before calling the build ready.'], { ...critical, priority: 22, requires: ['dps-open'], time: '20–40 min', reward: 'Main rotation learned', sources: ['a499Practice', 'catalyst'], note: 'No universal number of A499 shots guarantees a holster tick: your reload speed and timings matter. Check the magazine before swapping back.' });
task('dps-recover', 'rotation', 'Practice when the phase goes wrong', ['Missed Still Hunt crit: continue until its meter is full; spend one reload or a holster interval instead of attempting an uncharged special shot.', 'Missed Nighthawk shot: accept the lost burst and continue the weapon loop. Do not stop damage waiting for another Super.', 'Boss moved / crit hidden: reposition or use the safer heavy option. Do not empty precision ammo into an immune phase.', 'Radiant or debuffs dropped: refresh the missing effect when safe; distinguish your outgoing buff from the debuff on the boss.', 'Armor Charge expired: collect a reachable Orb between attacks. Do not cross a lethal lane just to refresh surges.', 'Out of heavy: continue accurate Still Hunt shots, use remaining charged shots, and clear adds between phases to recover ammo.', 'Save the main loadout and export your checklist backup. You are ready for the post-A499 roadmap.'], { ...critical, priority: 23, requires: ['dps-loop'], time: '15–25 min', reward: 'Functional build complete', why: 'Consistent damage through mistakes matters more than reproducing an ideal video opener.', sources: ['aggregate', 'a499Practice'] });

task('hezen-get', 'hezen', 'Secondary: earn current Hezen Vengeance', ['Join a six-player Vault of Glass teaching group. Select its current entry under Raids and Dungeons.', 'Complete through Gatekeepers and Atheon; check those encounter rewards for Hezen. Keep a current reprised copy.', 'When Vault of Glass is featured, repeat suitable encounters for loot. Use the raid vendor’s weekly Deepsight purchase after unlocking the weapon.', 'Track five pattern extractions, then craft at the Enclave when the pattern is complete. Inspect the recipe for current material costs.'], { tags: ['Raid', 'Farming', 'Optional'], tier: 'Secondary loadout', requires: ['dps-recover'], time: '1.5–3 hr first clear; pattern farm varies', team: '6, communication recommended', gate: 'Weapon RNG; weekly Deepsight purchase', location: 'Raids and Dungeons → Vault of Glass', reward: 'Hezen Vengeance / crafting pattern', sources: ['hezen', 'patch'] });
task('hezen-roll', 'hezen', 'Secondary: choose a simple rocket roll', ['Start with Auto-Loading Holster + Elemental Honing or Aggregate Charge; both are in the current reprised pool.', 'Keep Envious Arsenal + Bait and Switch as an alternative when you reliably damage with all three weapons.', 'Inspect the actual current magazine and perks. Do not copy a multi-rocket video assuming every Hezen roll has overflowed ammo.', 'Save “Nighthawk · Hezen” with Solar support. Keep A499 in the main loadout.'], { tags: ['Raid', 'Optional'], requires: ['hezen-get'], time: '10–20 min plus roll acquisition', gate: 'Random rolls / pattern crafting', reward: 'Secondary burst roll', sources: ['hezen'] });
task('hezen-compare', 'hezen', 'Decide when Hezen is better for you', ['Try it for a short damage window where rapid rocket burst and shared Solar support fit the boss.', 'Coordinate with a teammate’s Gjallarhorn if the team is using rockets. Avoid firing into nearby teammates or cover.', 'Compare with A499 on the same encounter. Favor A499 when you have a reliable crit spot and a longer sustained window.', 'Use a safer heavy when a boss constantly hides its crit spot. Treat “Hezen beats A499” as encounter- and team-dependent, not a universal claim.'], { tags: ['Optional'], requires: ['hezen-roll'], time: '20–40 min', reward: 'Encounter-specific secondary choice', why: 'This is a practical comparison plan. No controlled October benchmark was verified for your exact roll and team.', sources: ['hezen', 'a499Practice'] });

task('after-choice', 'endgame', 'After A499: use the hybrid route', ['Check that the main loadout and recovery loop are functional, not necessarily perfect.', 'Spend one or two sessions on a targeted armor upgrade: Vault of Glass for orb sustain or Spire for fresh-draw precision damage.', 'Then return to Shadowkeep → Beyond Light → Witch Queen → Lightfall and the remaining story. Raid when the group and featured rewards align.', 'Switch the roadmap preference to Story if you want narrative first, or Endgame if your group is ready now. Either route can progress independently.'], { tags: ['Raid', 'Farming'], branch: 'endgame', priority: 100, requires: ['dps-recover'], time: '5 min decision', reward: 'An explicit post-A499 plan', why: 'Recommendation: functional build → one meaningful gear target → campaign catch-up. You do not need a tour of every raid before enjoying the story.', sources: ['sets', 'patch'] });
task('endgame-target', 'endgame', 'Pick one armor upgrade that changes the build', ['Option A: four current Atheon’s Memory pieces from Vault of Glass in arms, chest, legs and cloak. Collective Power makes Orbs during sustained damage while a subclass buff is active.', 'Option B: four current TM-Earp / TM Custom pieces from Spire of the Watcher in those same non-helmet slots. High Noon rewards freshly drawn precision weapons.', 'Keep Nighthawk in the helmet slot. Do not accidentally equip a set helmet and lose the Exotic.', 'Farm the chosen activity when featured for Tier 5 armor. Compare the complete four-piece set with your current loadout before dismantling replacements.', 'Choose orb sustain or fresh-draw damage based on your actual loop. Neither is mandatory for your first raid.'], { tags: ['Raid', 'Dungeon', 'Farming'], branch: 'endgame', priority: 101, requires: ['after-choice'], time: '2–6 hr across farm sessions', team: '6 for VoG / 3 for Spire', gate: 'Armor slot/archetype RNG; featured rotation', reward: 'Four-piece set with a real effect', sources: ['sets', 'spireSet', 'patch'] });
task('power-route', 'endgame', 'Use Ops for Power, raids for selected loot', ['Read your activity’s difficulty and reward preview before launching. Use a difficulty you can finish consistently.', 'For Power progression, seek A-grade-or-better Ops results; the cap is 550.', 'For build upgrades, prioritize the chosen set, weapon pattern or utility item. A random raid clear is not automatically an A499 upgrade.', 'Use Adventure difficulty for a lower-stakes teaching clear when offered; check its lower reward tier.', 'Do not postpone older fixed-difficulty story content solely to reach the Power cap.'], { tags: ['Farming'], branch: 'endgame', priority: 102, requires: ['after-choice'], time: '20–40 min per session', team: 'Solo / matchmade / premade by activity', reward: 'Power progression without an unfocused raid grind', sources: ['patch', 'stats', 'launch'] });
task('utility-raids', 'endgame', 'Choose your next raid for a specific reason', ['Vault of Glass: your first targeted armor farm and optional Hezen pattern; both relate directly to this setup.', 'Deep Stone Crypt: a manageable learning raid and useful Legendary utility options such as Heritage / Succession; these are alternate loadout tools.', 'Vow of the Disciple: Forbearance gives another add-clear tool, but shares the energy slot with Still Hunt. Use it between damage phases or in another loadout.', 'Root of Nightmares: Conditional Finality is a useful alternate Exotic; it cannot be paired with Still Hunt.', 'Last Wish: Apex Predator is a secondary rocket option; do not chase it before a working A499 just because older guides call it mandatory.', 'Salvation’s Edge / The Desert Perpetual: learn them for mechanics and their specific loot, not as prerequisites to the build. Enter with a teaching group.'], { tags: ['Raid', 'Exotic'], branch: 'endgame', priority: 110, requires: ['after-choice'], time: '1.5–4 hr each first learning clear', team: '6 with voice / clear communication', gate: 'Patterns or Exotic RNG depend on activity', reward: 'Useful alternate loadouts and raid experience', sources: ['current', 'sets'], note: 'The current record tracker covers every raid. These priorities are editorial recommendations for this Hunter, not an exhaustive weapon tier list.' });
task('utility-dungeons', 'endgame', 'Choose dungeons for practical upgrades', ['Spire of the Watcher: prioritize its current precision-swap set if that is your chosen armor plan.', 'Warlord’s Ruin: Indebted Kindness is a useful Legendary Arc special for general play; it replaces Still Hunt while equipped.', 'Vesper’s Host / Sundered Doctrine / Equilibrium: learn them once the build is comfortable. Check current armor perks and encounter loot before repeated farming.', 'Prophecy: a lower-commitment teaching option and a current armor set for mixed Light/Dark play.', 'Keep dungeon Exotics and solo-flawless goals optional. More clears do not automatically improve your main three-weapon loadout.'], { tags: ['Dungeon', 'Farming'], branch: 'endgame', priority: 111, requires: ['after-choice'], time: '1–3 hr each learning clear', team: '3 recommended', gate: 'Targeted loot / Exotic RNG', reward: 'Useful general-play gear and mechanics practice', sources: ['current', 'sets'] });

task('story-start', 'story', 'Set the campaign catch-up order', ['Use the Expansions/Timeline and destination campaign nodes to find your current campaign milestones.', 'Mark missions you actually finished; prior ownership alone does not complete them.', 'Use Normal difficulty for the shortest story catch-up. Legendary campaigns are a separate optional challenge.', 'After the build is functional, play the ordered campaign tasks below. Endgame farming can happen alongside this route.'], { tags: ['Story'], branch: 'story', priority: 100, requires: ['dps-recover'], time: '5 min', reward: 'Narrative route ready', sources: ['current'] });
task('shadowkeep', 'story', 'Shadowkeep cleanup · Moon', ['Start A Mysterious Disturbance, then speak to Eris at Sanctuary.', 'Complete In Search of Answers, cleanse the Essence of Despair through Moon activities, and return to Eris.', 'Complete Ghosts of Our Past for the Essence of Anguish.', 'Complete The Scarlet Keep strike and cleanse Anguish using its displayed requirements; return to Eris.', 'Complete In the Deep for the Cryptoglyph, then unlock the Lectern and claim the Dreambane piece.', 'Speak to Ikora through the Sanctuary portal. Complete the Skolas, Taniks and Phogoth Nightmare hunts and their associated Essences.', 'Equip the required Dreambane set, speak to Eris for The Pyramid Awaits, then complete Beyond.', 'Finish Eris, Zavala and Ikora handoffs. Park repeat Essence farms and weekly Memories.'], { tags: ['Story'], branch: 'story', priority: 101, requires: ['story-start'], time: '3–6 hr if starting fresh', location: 'Moon → Eris / Lectern', reward: 'Shadowkeep narrative complete', sources: ['moonStory', 'current'], note: 'Old guides list vaulted patrol destinations and obsolete Power targets. Use available Nightmare Lost Sectors and your current Essence tooltip. Garden and Pit are separate activities.' });
task('beyond-light', 'story', 'Beyond Light · Europa', ['Track the Beyond Light campaign with Variks / the Exo Stranger.', 'Play Darkness’s Doorstep and the following Europa campaign objectives.', 'Complete The New Kell → Rising Resistance → The Warrior → The Technocrat → The Kell of Darkness, with the intervening patrol/quest steps.', 'Visit the Exo Stranger afterward and inspect Stasis unlocks / Born in Darkness options.', 'Buy or finish only the Stasis abilities you want for a separate Stasis loadout. Prismatic’s starting Withering Blade is already available.'], { tags: ['Story'], branch: 'story', priority: 102, requires: ['shadowkeep'], time: '4–7 hr', location: 'Europa', reward: 'Beyond Light / Stasis audit', sources: ['europaStory', 'current', 'prismatic'] });
task('witch-queen', 'story', 'The Witch Queen · Throne World', ['Complete The Arrival → The Investigation → The Ghosts → The Communion.', 'Continue The Mirror → The Cunning → The Last Chance → The Ritual.', 'Follow the evidence board / Enclave tutorials between missions; unlock weapon crafting through the introduction.', 'Claim Ikora’s completion reward and audit Parasite / Evidence Board quests separately.', 'Use Normal for this catch-up; save Legendary replay for a deliberate challenge.'], { tags: ['Story'], branch: 'story', priority: 103, requires: ['beyond-light'], time: '6–9 hr', location: 'Throne World / Enclave', reward: 'Witch Queen story and crafting access', sources: ['witchStory', 'current'] });
task('lightfall', 'story', 'Lightfall · Neomuna', ['Complete First Contact → Under Siege → Downfall → Breakneck.', 'Continue On the Verge → No Time Left → Headlong → Desperate Measures.', 'Speak to Nimbus and finish the post-campaign handoffs; inspect your separate Strand subclass.', 'Spend Strand Meditations at the Pouka Pond only for desired Strand abilities / fragments.', 'Park deterministic Exotic side quests for later unless their reward is your next chosen target.'], { tags: ['Story'], branch: 'story', priority: 104, requires: ['witch-queen'], time: '5–8 hr', location: 'Neomuna / Hall of Heroes', reward: 'Lightfall story and Strand', sources: ['lightfallStory', 'current'] });
task('final-shape-cleanup', 'story', 'The Final Shape cleanup', ['Verify Excision and Ghost’s ending dialogue are complete.', 'Finish Destined Heroes / Ergo Sum and the remaining six Prismatic adventures if desired.', 'Progress Micah-10’s lost Ghost / Cyst stories and record missing fragments.', 'Choose one optional Exotic: Microcosm cooperative focus, Khvostov collection, or Dual Destiny for the Exotic class item.', 'For Dual Destiny, complete Overthrow in each main Pale Heart region and the post-Overthrow Secret-Keeper checks, then follow the unlock encounter. Bring a communicating partner.', 'Keep Relativism as a separate build: Nighthawk occupies the Exotic armor slot here.'], { tags: ['Story', 'Prismatic', 'Exotic'], branch: 'story', priority: 105, requires: ['lightfall', 'excision'], time: '4–12 hr depending on collection goals', team: 'Solo exploration; 2 Dual Destiny; 3 cooperative focus', reward: 'Pale Heart catch-up', sources: ['current', 'facetAudit', 'heroes'], note: 'Optional Exotic-specific collectible counts and Dual Destiny encounter details are linked/quest-led, not a prerequisite to A499.' });
task('edge-fate', 'story', 'The Edge of Fate · Kepler entry', ['Open Kepler / The Edge of Fate in Destinations and track the campaign.', 'Choose Normal for a short catch-up, or deliberately choose Legendary for the additional challenge.', 'Complete The Invitation and meet Ikora / Lodi as prompted.', 'Keep the active Central Academy / region quest tracked. Kepler has a non-linear middle section; the mission record below follows the linked guide’s order, not a universal forced branch order.'], { tags: ['Story'], branch: 'story', priority: 106, requires: ['final-shape-cleanup'], time: '25–45 min entry', location: 'Kepler', reward: 'Kepler campaign started', sources: ['keplerStory', 'current'] });
task('edge-missions', 'story', 'The Edge of Fate · mission record', ['Fallow: use the region quest and its Vex shield / Matterspark objectives.', 'Nostos: charge the Fallen terminal with Matterspark-earned motes and finish the boss phases.', 'Commencement: complete the Central Academy branch.', 'Transient: complete the marked campaign mission.', 'Saturnism: complete the marked campaign mission.', 'Gouge: complete the marked campaign mission.', 'Morphology: complete the marked campaign mission.', 'Charge: complete the marked campaign mission.', 'Disruption: complete the marked campaign mission.', 'Calculus: complete the marked campaign mission.', 'Quarantine: complete the marked campaign mission.', 'Criticality: complete the marked campaign mission.', 'The Message: finish the campaign ending and collect pending dialogue / rewards.', 'Audit destination Exotics and exploration later. Record The Desert Perpetual separately as a raid.'], { tags: ['Story'], branch: 'story', priority: 106.5, requires: ['edge-fate'], time: '6–10 hr full campaign estimate', team: 'Solo or 1–3', location: 'Kepler region quests', reward: 'Kepler campaign complete', sources: ['keplerStory'], note: 'The illustrated source covers the region puzzles. Follow your quest’s branch order and route upgrades where the map differs; this is a mission-level completion record.' });
task('ren-story-catchup', 'story', 'Renegades and the current era', ['If you already completed the main story while farming A499, mark this audit complete.', 'Otherwise return to the main Renegades quest: Fearsome Retainer → Out in the Cold → Fire and Ice → The Long Con → Glory Beyond, with the marked jobs between missions.', 'Finish Spider / Drifter handoffs and optional Lawless stories that interest you.', 'Explore Monument of Triumph / Distortions and the permanent Pantheon when ready. There is no need to race an expiring season for this checklist.'], { tags: ['Story'], branch: 'story', priority: 107, requires: ['edge-missions'], time: '0–7 hr depending on earlier progress', location: 'Lawless Frontier / Tower', reward: 'Campaign catch-up through current content', sources: ['campaign', 'current'] });
task('vaulted-recaps', 'story', 'Read or watch the chapters you cannot play', ['Recap Red War → Curse of Osiris → Warmind → Forsaken’s campaign if you want the full history.', 'Recap the seasons between Shadowkeep and Beyond Light, then Hunt → Chosen → Splicer → Lost before Witch Queen.', 'Recap Risen → Haunted → Plunder → Seraph before Lightfall, then Defiance → Deep → Witch → Wish before The Final Shape.', 'Use the in-game Timeline reflections where offered. A returned activity or Exotic mission does not restore an entire vaulted seasonal campaign.', 'Check the current DCV list for any disputed availability; do not add vaulted campaign completion to your playable-task progress.'], { tags: ['Story', 'Optional'], requires: ['story-start'], time: '1–6 hr depending on recap depth', reward: 'Narrative context', sources: ['vault', 'current'] });

task('log-keep', 'cleanup', 'Keep the build and unlock quests easy to find', ['Track Destined Heroes / Wild Card until Still Hunt is claimed.', 'Track Renegades until Piker access and the relevant campaign features are open.', 'Keep desired Prismatic unlock quests and the active campaign visible; untrack unrelated tasks.', 'Before abandoning anything, identify its recovery vendor / Quest Archive and note whether it has progress you care about.'], { tags: ['Optional'], requires: ['audit'], time: '10–20 min', reward: 'Readable quest log', why: 'Parking a quest is safer than bulk deletion. Reacquisition does not guarantee every sub-step is preserved.', sources: ['faq'] });
task('log-pvp', 'cleanup', 'PvP onboarding can wait', ['Park Crucible / Gambit introductions, Competitive placement, Trials access and PvP catalyst requirements unless you want to play them.', 'Do not grind a Guardian Rank objective just because an old guide says it unlocks more loadout slots; check current rewards.', 'Keep any onboarding quest that your game explicitly requires for a locked system. Everything else can wait for the build.'], { tags: ['Optional'], requires: ['audit'], time: '5 min', reward: 'Less PvP pressure', sources: ['current', 'patch'] });
task('log-exotics', 'cleanup', 'Old catalysts and Exotic quests can wait', ['Park long catalysts for weapons you do not use. Work on Still Hunt’s optional catalyst naturally when it drops.', 'Save Spoils and Ciphers for a chosen purchase; do not buy every Monument to Lost Lights weapon before acquiring Nighthawk.', 'Keep deterministic dungeon / Exotic unlock quests if you plan to run with friends, but do not treat their reward as needed for this build.', 'Do not dismantle old Exotics for an assumed infusion cap. Inspect the current item and preserve useful catalysts / crafted weapons.'], { tags: ['Exotic', 'Optional'], requires: ['audit'], time: '5–10 min', reward: 'A small active quest list', sources: ['faq', 'cipher'] });

const raidList = [
  ['last-wish', 'Last Wish', 'Forsaken · D2', 'Dreaming City', 'Forsaken Pack', 'Kalli → Shuro Chi → Morgeth → Vault → Riven → Queenswalk', 'Apex secondary rocket; One Thousand Voices alternate Exotic'],
  ['garden', 'Garden of Salvation', 'Shadowkeep · D2', 'Moon', 'Shadowkeep Pack', 'Evade → Summon → Consecrated Mind → Sanctified Mind', 'Divinity team utility; keep it separate from Still Hunt'],
  ['dsc', 'Deep Stone Crypt', 'Beyond Light · D2', 'Europa', 'Beyond Light Pack', 'Crypt Security → Atraks-1 → Descent → Taniks', 'Heritage / Succession utility and a good teaching raid'],
  ['vog', 'Vault of Glass', 'Reprised D1 · 2021', 'Venus / Raids and Dungeons', 'Free', 'Spire → Confluxes → Oracles → Templar → Gorgons → Gatekeepers → Atheon', 'Atheon’s Memory set; current Hezen Vengeance'],
  ['vow', 'Vow of the Disciple', 'The Witch Queen · D2', 'Throne World', 'The Witch Queen', 'Acquisition → Caretaker → Exhibition → Rhulk', 'Forbearance alternate energy weapon; patterns'],
  ['kings-fall', 'King’s Fall', 'Reprised D1 · 2022', 'Dreadnaught / Raids and Dungeons', 'Free', 'Opening → Totems → Warpriest → Golgoroth → Daughters → Oryx', 'Story and learning; no required Nighthawk weapon'],
  ['root', 'Root of Nightmares', 'Lightfall · D2', 'Neptune orbit / Raids and Dungeons', 'Lightfall', 'Cataclysm → Scission → Explicator → Nezarec', 'Conditional Finality is an alternate Exotic, not a Still Hunt companion'],
  ['crota', 'Crota’s End', 'Reprised D1 · 2023', 'Moon / Raids and Dungeons', 'Free', 'Abyss → Bridge → Ir Yût → Crota', 'Armor / alternate loot; sword-focused boss changes your loadout'],
  ['salvation', 'Salvation’s Edge', 'The Final Shape · D2', 'Pale Heart', 'The Final Shape', 'Substratum → Dissipation → Repository → Verity → Witness', 'Advanced mechanics and story; not needed to unlock Still Hunt'],
  ['desert', 'The Desert Perpetual', 'The Edge of Fate · D2', 'Nine space / Raids and Dungeons', 'The Edge of Fate', 'Select the available encounter path; follow the raid’s Feat / encounter objectives', 'Current raid loot; inspect set and weapon targets before farming']
];
for (const [id, name, era, location, access, encounters, loot] of raidList) task('raid-' + id, 'raids', name, ['Confirm access: ' + access + '. Select the full raid in Raids and Dungeons.', 'Complete a teaching clear: ' + encounters + '.', 'Record a full clear; inspect rewards and lock useful drops.'], { tags: ['Raid', 'Optional'], tier: 'Completion record', era, location, team: '6; no automatic teaching matchmaking', time: '1.5–4 hr first clear; complex raids may take longer', gate: 'See current featured rotation; some purchases/chests are weekly', recommend: false, reward: loot, why: 'Track a clear once. This record does not reset at weekly reset or claim you have mastered every encounter.', sources: ['current'], note: 'Farm status and reward tiers are shown in the Director. Use the featured-activity rule card below, not a historical weekly rotation.' });
task('raid-pantheon', 'raids', 'Pantheon · permanent boss gauntlet', ['Open the permanent Pantheon entry under Raids and Dungeons.', 'Begin with an available Adventure teaching option and learn the selected bosses.', 'Record a clear and inspect the end vendor before spending Spoils.'], { tags: ['Raid', 'Optional'], tier: 'Optional gauntlet', era: 'Monument of Triumph · boss reprise, not restored full vaulted raids', team: '6', time: '2–4 hr learning run', reward: 'Pantheon loot / experience', recommend: false, sources: ['current', 'launch'], note: 'Original Leviathan, Eater of Worlds, Spire of Stars, Scourge of the Past and Crown of Sorrow are not represented as available full raids here.' });
task('featured-rule', 'raids', 'Check this week before repeated farming', ['Inspect the two featured raids and two featured dungeons in the Director; this site does not fetch the weekly rotation.', 'Featured raid encounters can provide farmable Deepsight / Tier 5 armor. Hidden chests and the weekly Deepsight purchase retain separate lockouts.', 'Featured dungeons provide farmable Tier 5 weapons and armor.', 'Read the Exotic’s own reward restrictions before assuming unlimited Exotic chances. Keep the first-clear record separate from farming attempts.'], { tags: ['Raid', 'Dungeon', 'Farming', 'Optional'], recommend: false, time: '2 min', gate: 'Weekly feature / purchase / chest lockouts', reward: 'A correct farm plan for the week', sources: ['patch'] });

const dungeonList = [
  ['shattered', 'The Shattered Throne', 'Forsaken', 'Dreaming City', 'Forsaken Pack', 'Erebus → Vorgeth → Dûl Incaru', 'Wish-Ender quest / catalyst; optional for this loadout'],
  ['pit', 'Pit of Heresy', 'Shadowkeep', 'Moon', 'Shadowkeep Pack; Deepening Wake quest if node locked', 'Necropolis → Tunnels → Chamber → Harrow → Zulmak', 'Xenophage quest; optional alternate heavy'],
  ['prophecy', 'Prophecy', 'Arrivals / Beyond Light era', 'Raids and Dungeons', 'Free', 'Phalanx Echo → Wasteland → Cube → Rainbow Road → Kell Echo', 'Current CODA set; a teaching option'],
  ['grasp', 'Grasp of Avarice', '30th Anniversary', 'Cosmodrome', '30th Anniversary Pack; And Out Fly the Wolves', 'Loot cave → Phry’zhia → Sparrow → Fallen Shield → Avarokk', 'Gjallarhorn supports a rocket team, replacing Still Hunt when equipped'],
  ['duality', 'Duality', 'The Witch Queen', 'Moon / Raids and Dungeons', 'Witch Queen Dungeon Key; A Single Thread', 'Gahlran → Vault → Caiatl', 'Alternate gear / Heartshadow'],
  ['spire', 'Spire of the Watcher', 'The Witch Queen', 'Mars / Raids and Dungeons', 'Witch Queen Dungeon Key; Ares Desperado', 'Circuit ascent → Akelous → Persys', 'TM Custom / High Noon is relevant to sniper swapping'],
  ['ghosts', 'Ghosts of the Deep', 'Lightfall', 'Titan / Raids and Dungeons', 'Lightfall Dungeon Key; Rise', 'Hive ritual → Ecthar → Simmumah', 'Alternate gear / The Navigator'],
  ['warlord', 'Warlord’s Ruin', 'Lightfall', 'EDZ', 'Lightfall Dungeon Key; In the Shadow of the Mountain', 'Rathil → Locus of Wailing Grief → Hefnd', 'Indebted Kindness utility; Buried Bloodline alternate Exotic'],
  ['vesper', 'Vesper’s Host', 'The Final Shape', 'Europa', 'Final Shape Dungeon Key; Rogue Network at Hawthorne', 'Activation → Raneiks Unified → Corrupted Puppeteer', 'Current gear / Ice Breaker alternate Exotic'],
  ['sundered', 'Sundered Doctrine', 'The Final Shape', 'Throne World', 'Final Shape Dungeon Key; The Drowning Labyrinth', 'Resolve the pyramid puzzles → encounter bosses → Kerrev', 'Current gear / Finality’s Auger alternate Exotic'],
  ['equilibrium', 'Equilibrium', 'Renegades', 'Lawless Frontier / Raids and Dungeons', 'Renegades / Year of Prophecy / current Collection', 'Follow the dungeon’s marked mechanics with a teaching group; record a full completion', 'Current dungeon gear; confirm a specific upgrade before farming']
];
for (const [id, name, era, location, access, encounters, loot] of dungeonList) task('dungeon-' + id, 'dungeons', name, ['Confirm access: ' + access + '. Collect an entry quest if the node requests one.', 'Complete a teaching clear: ' + encounters + '.', 'Record the full clear and keep any desired quest progress / loot.'], { tags: ['Dungeon', 'Optional'], tier: 'Completion record', era, location, team: '3 recommended; solo is a challenge option', time: '1–3 hr first clear', gate: 'Targeted loot RNG; inspect featured reward rules', recommend: false, reward: loot, sources: ['current'], note: 'Original destination names describe the activity’s setting. Use the new Raids and Dungeons node for access. The Collection includes all Dungeon Keys.' });

task('resource-budget', 'materials', 'Reserve materials for the next actual purchase', ['Fill the Inventory counts from your game. Blank means unknown; a typed zero means checked and empty.', 'Prioritize one Exotic Cipher + one Exotic Engram for Nighthawk if needed.', 'Keep Glimmer and upgrade materials for a tested loadout. Inspect the masterwork / tier-upgrade cost before confirming.', 'For A499, record Credits, Ingots and your Piker rank. Spend for Rank 2 access first; set a separate optional roll-hunt budget.', 'Export after a long session. Counts are manual snapshots and do not automatically decrease when you buy items in-game.'], { tags: ['Farming', 'Optional'], recommend: false, time: '5 min', reward: 'A small spending plan', sources: ['cipher', 'piker', 'faq'] });
task('resource-refill', 'materials', 'Refill only the resource that is blocking you', ['Glimmer: public events / ordinary play with a Glimmer-boosting Ghost mod; use Rahool exchange offers if you already own spare materials.', 'Cores / Prisms / Shards: inspect Ops, vendor and reward-track previews and run a reliable activity offering the material you need.', 'Ciphers: Xenology from Xûr and available reward tracks; the Chronolog Exchange has a weekly offer.', 'Credits / Ingots: combine a Lawless job with contracts, search loot containers, then exfil successfully.', 'Spoils: play raids and inspect eligible chest/encounter rewards. Do not buy a raid Exotic merely to consume your saved currency.'], { tags: ['Farming', 'Optional'], recommend: false, time: '20–60 min per session', gate: 'Some offers weekly; drops depend on activity', reward: 'Targeted refill', sources: ['lawless', 'cipher', 'patch'] });
task('retired-currencies', 'materials', 'Retire the old shopping list', ['Do not farm Legendary Shards or Upgrade Modules for this route; they were deprecated.', 'Check Rahool for conversion of eligible old materials.', 'Do not use old seasonal currencies, Nightfall Ciphers or expired event tickets as build-critical requirements.', 'Keep still-active destination currencies only if you have a specific purchase planned.'], { tags: ['Optional'], recommend: false, time: '5 min', reward: 'No obsolete resource grind', sources: ['faq', 'current'] });

task('keep-a499', 'watchlist', 'Keep A499 damage and reload options', ['Lock any Aggregate Charge A499 until compared with the equipped roll.', 'Lock Snapshot + Aggregate; also keep a useful Auto-Loading Holster variant.', 'Inspect for Accelerated Assault before dismantling. The ornament alone is not enough.', 'Keep the good lower-tier roll; later upgrading does not reroll its perks.'], { tags: ['Farming', 'Optional'], recommend: false, time: '2 min per batch', reward: 'Protected build rolls', sources: ['a499', 'accelerated', 'weapons'] });
task('keep-primary', 'watchlist', 'Keep a Kinetic primary and useful alternatives', ['Chroma Rush: keep Kinetic Tremors with a sensible reload / control perk; Bewildering Burst or Subsistence are useful candidates.', 'Inbound Surveillance: keep Shoot to Loot + Kinetic Tremors; ranged ammo / Orb pickup can support a sniper build.', 'Keep Hezen Auto-Loading / Elemental Honing, Aggregate or Envious Arsenal / Bait and Switch rolls for the secondary loadout.', 'Keep your preferred crafted raid utility weapons. Compare their current updated recipe before replacing them.'], { tags: ['Farming', 'Optional'], recommend: false, time: '5 min audit', reward: 'Useful primary and alternative heavies', sources: ['chroma', 'inbound', 'hezen'], note: 'These combinations are in the current database. A reliable existing primary is enough; popularity does not establish a universal best roll.' });
task('keep-armor', 'watchlist', 'Keep armor that fits a complete loadout', ['Lock Nighthawk; do not dismantle the working copy before testing its replacement.', 'Keep high Weapons / Super profiles, especially Powerhouse, with enough survival stats for your activity.', 'Keep four current non-helmet pieces of your chosen VoG or Spire set even while their archetypes are imperfect.', 'Keep Armor 2.0 raid pieces with useful raid-mod slots separately; current Armor 3.0 raid drops use set bonuses instead.', 'Compare the whole equipped build in an optimizer or in-game. A lower individual total can still complete a better loadout.'], { tags: ['Farming', 'Optional'], recommend: false, time: '5–10 min audit', reward: 'Protected stat and set options', sources: ['armor', 'sets'] });

export const resources = [
  { id: 'glimmer', name: 'Glimmer', cap: 500000, target: 100000, use: 'Working reserve for focusing and upgrades; target is a suggested reserve.', source: 'glimmer' },
  { id: 'cores', name: 'Enhancement Cores', cap: 9999, target: 50, use: 'Weapon/armor upgrades. Refill from activity or vendor previews.', source: 'patch' },
  { id: 'prisms', name: 'Enhancement Prisms', cap: 200, target: 20, use: 'Higher armor upgrades and exchanges.', source: 'patch' },
  { id: 'shards', name: 'Ascendant Shards', cap: 50, target: 5, use: 'Masterworking / eligible focusing. Reserve until the loadout is tested.', source: 'patch' },
  { id: 'alloys', name: 'Ascendant Alloy', cap: 50, target: 2, use: 'Enhanced crafting upgrades; optional before A499.', source: 'patch' },
  { id: 'ciphers', name: 'Exotic Ciphers', cap: 5, target: 1, use: 'Novel Exotic focusing / Monument to Lost Lights.', source: 'cipher' },
  { id: 'exotic-engrams', name: 'Exotic Engrams', cap: null, target: 1, use: 'Nighthawk focusing. Account inventory capacity applies.', source: 'stats' },
  { id: 'spoils', name: 'Spoils of Conquest', cap: null, target: 20, use: 'Raid purchases. Inspect cost and inventory cap in-game; current cap not independently confirmed.', source: 'patch' },
  { id: 'coins', name: 'Strange Coins', cap: 777, target: 71, use: 'Xûr; 71 is a catalyst shopping reserve, not a Nighthawk requirement.', source: 'patch' },
  { id: 'chronologs', name: 'Chronologs', cap: null, target: 500, use: 'Past-pass rewards and weekly exchange; a Cipher offer costs 500.', source: 'patch' },
  { id: 'marks', name: 'Legendary Marks', cap: null, target: null, use: 'Monument Triumphs → Guardian Tenet rewards. Optional.', source: 'current' },
  { id: 'credits', name: 'Lawless Credits', cap: null, target: null, use: 'A499 buying budget; check current Piker offer and daily discounts.', source: 'lawless' },
  { id: 'ingots', name: 'Dark Matter Ingots', cap: null, target: null, use: 'Piker War Chest → reputation / gear.', source: 'piker' },
  { id: 'piker-rank', name: 'Piker Rank', cap: 5, target: 2, use: 'Rank 2 opens A499 purchases; ranks 4/5 improve daily discounts.', source: 'piker' },
  { id: 'deathmarks', name: 'Deathmarks', cap: null, target: null, use: 'Optional Invasions; unnecessary for the main build.', source: 'lawless' },
  { id: 'hezen-pattern', name: 'Hezen pattern extractions', cap: 5, target: 5, use: 'Crafting pattern progress; the secondary loadout only.', source: 'hezen' },
  { id: 'still-kills', name: 'Still Hunt catalyst kills', cap: 500, target: 500, use: 'Optional catalyst objective; mark acquired separately.', source: 'catalyst' },
  { id: 'power', name: 'Gear Power', cap: 550, target: null, use: 'Manual gear-Power snapshot. Not a gate on the legacy story checklist.', source: 'patch' },
  { id: 'stat-weapons', name: 'Equipped Weapons stat', cap: 200, target: 100, use: 'Start at a practical 100; consider 200 for boss-weapon damage.', source: 'stats' },
  { id: 'stat-super', name: 'Equipped Super stat', cap: 200, target: 100, use: 'Actual Golden Gun; consider 200 later. Do not equate this with Still Hunt damage.', source: 'stats' },
  { id: 'stat-health', name: 'Equipped Health stat', cap: 200, target: null, use: 'Record your usable survival setup rather than an arbitrary mandatory number.', source: 'stats' },
  { id: 'stat-class', name: 'Equipped Class stat', cap: 200, target: null, use: 'Dodge uptime and enhanced class benefits.', source: 'stats' },
  { id: 'stat-melee', name: 'Equipped Melee stat', cap: 200, target: null, use: 'Melee uptime / damage; support Dawn as needed.', source: 'stats' },
  { id: 'stat-grenade', name: 'Equipped Grenade stat', cap: 200, target: null, use: 'Grenade uptime / damage; utility first for this weapon build.', source: 'stats' }
];

resources.push(
  { id: 'vestiges-light', name: 'Memory Vestiges · Light', cap: null, target: 5, use: 'Optional Prismatic collection: five form a Legendary Light Memory. Follow the resulting Memory before collecting more.', source: 'facetAudit' },
  { id: 'vestiges-dark', name: 'Memory Vestiges · Darkness', cap: null, target: 5, use: 'Optional Prismatic collection: five form a Legendary Dark Memory.', source: 'facets' },
  { id: 'strand-meditations', name: 'Strand Meditations', cap: null, target: null, use: 'Separate Strand subclass purchases at the Pouka Pond; not needed for the starting Prismatic kit.', source: 'lightfallStory' },
  { id: 'vanguard-ciphers', name: 'Vanguard Ciphers', cap: null, target: null, use: 'Pinnacle / Arena Ops focusing offers at Zavala. Confirm the current offer before farming.', source: 'patch' },
  { id: 'vog-set', name: 'VoG non-helmet set pieces', cap: 4, target: 4, use: 'Count arms, chest, legs and cloak; current Atheon’s Memory armor only.', source: 'sets' },
  { id: 'spire-set', name: 'Spire non-helmet set pieces', cap: 4, target: 4, use: 'Count arms, chest, legs and cloak; current TM Custom armor only.', source: 'spireSet' }
);

const retired = tasks.find(t => t.id === 'retired-currencies');
retired.steps[0].text = 'Do not farm Legendary Shards, Upgrade Modules or Unstable Cores for this route; they were deprecated.';
retired.steps.push({ id: 'retired-currencies.5', text: 'Ordinary infusion now costs one Enhancement Core and 5,000 Glimmer. Inspect the actual item’s cost before confirming.' });
retired.sources.push('infusion');

export const glossary = {
  'RNG': 'Random outcome. Repeating an activity may not give the item or roll you want.',
  'Weekly gated': 'A reward or purchase has a weekly limit. Checking it here does not reset it in-game.',
  'Deepsight': 'A red-border weapon can grant progress toward its crafting pattern. Extract the pattern before dismantling.',
  'Armor Charge': 'A temporary resource commonly gained from Orbs. Surges use it over time; other mods may spend it.',
  'Radiant': 'A Solar outgoing weapon-damage buff. It is a buff on you, not a debuff on the boss.',
  'Debuff': 'An effect applied to a target, such as Slow, Sever, Scorch or Weaken. Aggregate Charge counts distinct elemental debuffs.',
  'DPS': 'Damage per second. A damage phase is the period when a boss is vulnerable.',
  'Tier': 'Gear quality. A good perk roll can matter more than tier, and weapon upgrading does not add new alternative perks.',
  'Exfil': 'Exit a Lawless job through its extraction point to bank completion and certain loot.',
  'Origin trait': 'An extra perk tied to a weapon’s source. Inspect it; a cosmetic ornament does not prove it is present.',
  'Aspect / Facet': 'Aspects define subclass behavior. Facets are Prismatic fragments that add smaller effects.',
  'Attunement': 'A preference for eligible rewards, chosen in Inventory. It does not make every activity drop the weapon.',
  'Build Critical': 'Needed for the functional route chosen here, including learning the rotation. It does not mean all such tasks are game-enforced unlocks.'
};

// Presentation labels can change without remapping any saved checks.
const shortSteps = {
  'heroes-radio': ['Return to the Lost City Tower.', 'Speak to Ghost; listen to his radio. Track Destined Heroes.'],
  'queens-one': ['Launch Queens, Part I from the Lost City banner.', 'Reflect Hive projectiles with the sword guard; finish the adventure.', 'Speak to Micah-10 at the Arbor of Light. Accept Rootbound.'],
  'wild-accept': ['Speak to Cayde-6 in the Lost City.', 'Accept Wild Card; find the rooftop banner.', 'If missing, check the quest objective and Quest Archive.'],
  'still-hunt': ['Launch Wild Card from the rooftop banner.', 'Follow Cayde and Crow; collect Dark Ether and investigate.', 'Defeat Lii’liks and finish the mission.', 'Use the Lost City radio; speak to Cayde and claim Still Hunt.'],
  'excision': ['Find Excision at the right edge of the Pale Heart map.', 'Complete the 12-player narrative mission.', 'Watch the ending; collect Ghost’s remaining rewards.'],
  'ergo-chain': ['Accept Lost in the Light and Found in the Dark from Ghost.', 'Complete The Hollow I and II.', 'Complete Home I and II.', 'Complete Queens II; collect the Dyadic Prism from Ghost.', 'Take the Prism to the Sacrarium; claim Ergo Sum.'],
  'convalescence': ['Finish Rootbound → Underbrush → Greenery with Micah-10.', 'Accept Budding; assemble three players.', 'Complete cooperative-focus Ascent, Dissent and Iconoclasm.', 'Return to Micah-10 for Microcosm.'],
  'prism-core': ['Equip Golden Gun — Marksman.', 'Equip Marksman’s Dodge.', 'Equip Withering Blade.', 'Equip Duskfield Grenade.', 'Equip Stylish Executioner + Winter’s Shroud.', 'Choose your preferred jump.'],
  'prism-facets': ['Equip Dawn: melee hits grant Radiant.', 'Equip Courage: Slow the target before Golden Gun.', 'Equip Purpose: Orbs give Restoration with Golden Gun.', 'Equip Protection: resistance while surrounded.', 'Equip Hope; add Ruin if another slot is available.'],
  'nighthawk-owned': ['Already owned? Equip and lock Nighthawk.', 'Otherwise open Rahool’s Novel focusing as Hunter.', 'Focus Nighthawk: 1 Exotic Engram + 1 Exotic Cipher. Check the offer.', 'Alternative: buy from Xûr when stocked, or decrypt engrams.', 'Keep a working copy; optimize its stats later.'],
  'temporary': ['Equip an owned Legendary primary.', 'Equip Still Hunt + a reliable Legendary heavy.', 'Equip Nighthawk and the Prismatic kit above.', 'Add Siphon, loaders, chest resistances and orb healing.', 'Save “Nighthawk · interim”.'],
  'ren-start': ['Open Renegades in Destinations; track its introduction.', 'Complete Imperium.', 'Speak to Zavala, then Drifter at Tharsis Cantina.'],
  'ren-cantina': ['Speak to the Piker Bouncer.', 'Meet Aunor at the marked Cantina seat.', 'Speak to Drifter’s Ghost, then Drifter.', 'Play Drifter’s recording.', 'Collect the three marked Ghost parts in the Bazaar.', 'Speak to Spider.'],
  'ren-welcome': ['Launch Welcome to the Frontier.', 'Complete the package objective and exfiltrate.', 'Return to Spider for the Ghost components.', 'Speak to Blue; collect the reward and main campaign quest.'],
  'piker-rank': ['Visit Mechanic Deoriks and the Piker War Chest.', 'Complete Lawless jobs/contracts for Credits and Ingots.', 'Deposit Dark Matter Ingots into the Piker War Chest.', 'Reach Piker Rank 2; confirm A499 is purchasable.'],
  'a499-first': ['Check the Piker A499 price and daily discount.', 'Buy A499, or keep a Piker War Chest drop.', 'Confirm it is the Kinetic heavy sniper.', 'Lock the first usable copy.'],
  'a499-roll': ['Target Snapshot Sights + Aggregate Charge; favor reload speed.', 'Keep any Aggregate Charge roll while learning.', 'Keep Auto-Loading Holster as an alternative roll.', 'Gutshot helps body shots, not precision damage.', 'Apply elemental debuffs for Aggregate Charge.', 'Stop with a usable roll; perfect it later.'],
  'ren-campaign': ['Follow the marked campaign jobs and dialogue.', 'Fearsome Retainer → Out in the Cold → Fire and Ice → The Long Con → Glory Beyond.', 'Collect Spider/Drifter’s final rewards.', 'Check alliance banners and daily Priority Contracts.'],
  'finished-loadout': ['Equip Legendary primary + Still Hunt + A499 + Nighthawk.', 'Equip Marksman Golden Gun, Dodge, Blade, Duskfield and the starting Aspects.', 'Equip Dawn, Courage, Purpose, Protection and Hope.', 'Add Kinetic Loader and Solar support.', 'Save “Nighthawk · A499”.'],
  'mods-core': ['Helmet: matching Siphon; ammo support if it fits.', 'Arms: Kinetic Loader; Solar Loader/Dexterity as needed.', 'Chest: encounter-appropriate resistances.', 'Legs: Solar Holster, orb healing and Kinetic Surge if it fits.', 'Class item: Time Dilation for surges; optional dodge utility.', 'Check armor energy costs before fitting extra mods.'],
  'stat-plan': ['Use current Weapons, Health, Class, Melee, Grenade and Super stats.', 'Start toward 100 Weapons; 200 is a later damage target.', 'Super above 100 improves actual Golden Gun.', 'Keep enough survival and ability uptime.', 'Record equipped stats after mods and fragments.'],
  'artifact-main': ['Check S29 Encrypted Data Disk: Sniper’s Meditation and Reload at Range.', 'Compare Hunter’s Journal for a Still Hunt-led setup.', 'Read current perk tooltips; use one artifact at a time.', 'Save artifact selections with the loadout; check Champion coverage.'],
  'dps-prep': ['Rally or collect ammo; check reserves.', 'Charge Still Hunt and your actual Golden Gun separately.', 'Agree on buffs/debuffs; apply Slow when useful.', 'Refresh Radiant and collect Armor Charge.', 'Aim at the crit spot; wait for vulnerability.'],
  'dps-open': ['Fire a charged Still Hunt precision shot.', 'Cast Golden Gun and land the Nighthawk crit.', 'Swap to A499; fire and manually reload.', 'Adjust the opener to the boss’s damage window.'],
  'dps-loop': ['Fire/reload A499 accurately.', 'Charge Still Hunt with regular precision shots.', 'Stow Still Hunt for Solar Holster while using A499.', 'Return, finish charging, then special-reload the charged shot.', 'Practice normal reloads before animation shortening.', 'Complete three clean practice attempts.'],
  'dps-recover': ['Missed Still Hunt crit: keep charging; reload or use Holster.', 'Missed Golden Gun: continue weapon damage.', 'Boss moved: reposition; avoid wasting precision ammo.', 'Buffs expired: refresh them when safe.', 'Armor Charge expired: pick up a safe Orb.', 'Heavy empty: use Still Hunt; recover ammo between phases.', 'Save the loadout and export progress.']
};
for (const t of tasks) {
  for (const [i, step] of t.steps.entries()) if (shortSteps[t.id]?.[i]) step.short = shortSteps[t.id][i];
  if (t.id === 'audit') { t.tags = ['Optional']; t.recommend = false; }
  t.requires = t.requires.map(id => id === 'audit' ? 'iconoclasm' : id);
}

export const needs = {
  'heroes-radio': 'No materials', 'queens-one': 'No materials', 'wild-accept': 'No materials', 'still-hunt': 'No materials', 'excision': 'No materials',
  'ergo-chain': 'Dyadic Prism · quest reward', 'convalescence': 'No purchase · 3-player cooperative missions',
  'prism-core': 'Starting unlocks · no materials', 'prism-facets': 'Starting fragments · no materials',
  'nighthawk-owned': 'If missing: 1 Exotic Engram + 1 Exotic Cipher',
  'nighthawk-tune': 'Focusing / masterwork costs · check the item',
  'ren-start': 'Renegades access · no material purchase', 'ren-cantina': '3 Ghost parts · collect from quest markers', 'ren-welcome': 'Courier package · mission pickup',
  'piker-rank': 'Dark Matter Ingots → Piker reputation; reach Rank 2', 'a499-first': 'Credits · current Piker shop price', 'a499-farm': 'Credits + Ingots · set your own budget',
  'a499-roll': 'No extra cost to keep/test a roll', 'mods-core': 'Armor energy · inspect equipped pieces',
  'stat-plan': 'No fixed material requirement', 'artifact-main': 'Artifact unlocks · no focusing purchase',
  'facet-chests': '5 Light/Darkness vestiges per Memory', 'hezen-get': '5 Deepsight pattern extractions to craft',
  'catalyst-still': 'Catalyst acquired + 500 kills', 'endgame-target': '4 matching non-helmet armor pieces'
};

sources.khvostov = { title: 'Shacknews · Khvostov unlock', url: 'https://www.shacknews.com/article/140289/unlock-khvostov-7g-0x-destiny-2', kind: 'Quest walkthrough', date: '2024-06-17 · checked 2026-10-07' };
sources.dual = { title: 'Shacknews · Dual Destiny unlock', url: 'https://www.shacknews.com/article/140650/unlock-dual-destiny-destiny-2', kind: 'Quest walkthrough', date: '2024 · checked 2026-10-07' };
task('khvostov', 'finale', 'Khvostov · optional collection', ['Progress Micah-10 to Alone in the Dark; unlock all six Cysts.', 'Collect 15 Lost Encryption Bits: 9 regional chests + 6 Cysts.', 'Open the legendary Khvostov chest between the Impasse and Divide.', 'Collect 17 Motes of Light: 9 unique Overthrow bosses + 8 Visions of the Traveler.', 'Place the eight Visions at the old Speaker area in the Lost City; open the Exotic chest.'], { tags: ['Exotic', 'Optional'], requires: ['queens-one'], time: '3–6 hr', reward: 'Khvostov', sources: ['khvostov'], why: 'Pale Heart collection goal. The Exotic cannot share a loadout with Still Hunt.' });
task('dual-destiny', 'finale', 'Dual Destiny · optional class item', ['Finish Overthrow in the Landing, Blooming and Impasse.', 'After each clear, defeat that region’s Secret-Keeper during the cooldown.', 'Follow the green beam from the Blooming; complete the Light/Dark orb unlock encounter.', 'Bring a communicating partner and complete Dual Destiny.'], { tags: ['Exotic', 'Prismatic', 'Optional'], requires: ['excision'], time: '1–2 hr unlock + first clear', team: '2 players; communication required', reward: 'Relativism', sources: ['dual'], why: 'Unlock a separate Prismatic build. Relativism cannot be equipped with Nighthawk.' });
needs.khvostov = '15 Lost Encryption Bits + 17 Motes of Light + 8 Visions';
needs['dual-destiny'] = 'No purchase · 2 communicating players';
resources.push(
  { id: 'lost-bits', name: 'Lost Encryption Bits', cap: null, target: 15, use: 'Khvostov: 9 regional chests + 6 Cysts. They become a code when complete.', source: 'khvostov' },
  { id: 'motes-light', name: 'Motes of Light', cap: null, target: 17, use: 'Khvostov: 9 unique Overthrow bosses + 8 Visions. Converted/used by the quest.', source: 'khvostov' },
  { id: 'traveler-visions', name: 'Visions of the Traveler', cap: 8, target: 8, use: 'Place all eight at the old Speaker area for the Khvostov chest.', source: 'khvostov' }
);

export const paths = [
  { id: 'now', title: 'After Iconoclasm', tasks: tasks.filter(t => (t.tags.includes('Build Critical') && t.section !== 'position') || ['excision', 'ren-campaign'].includes(t.id)).map(t => t.id) },
  { id: 'extras', title: 'Pale Heart & build extras', tasks: tasks.filter(t => t.tags.includes('Optional') && ['finale', 'prismatic', 'nighthawk', 'build', 'renegades'].includes(t.section)).map(t => t.id) },
  { id: 'later', title: 'After A499', tasks: tasks.filter(t => ['endgame', 'story', 'hezen'].includes(t.section)).map(t => t.id) }
];

export default { version: 1, checkedOn: '2026-10-06', sections, tasks, resources, sources, glossary, needs, paths };
